name: openbench
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python>=3.11
  - netCDF4>=1.5.7
  - xarray>=0.19.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - joblib>=1.1.0
  - dask>=2022.1.0
  - cartopy>=0.20.0
  - flox>=0.5.0
  - cftime>=1.5.0
  # - tqdm>=2.2.0
  # - cdo>=1.9.10
  # - statsmodels
  # - xesmf